claude_model:
  sonnet: claude-sonnet-4-5-20250929  # for claude code version 2.0.65
  haiku: claude-haiku-4-5-20251001    # for claude code version 2.0.65

server: # optional, if you don't provide this field random port and token will be provided.
  port: 35421  # omit or set 0 to pick a random unused port
  token: dummy # token for ANTHROPIC_AUTH_TOKEN

provider_model:
  model: openrouter/openai/gpt-5.5  # follow the model name format of litellm
  base_url: https://openrouter.ai/api/v1
  api_key: your_api_key
  reasoning:
    effort: high
  # put other litellm model arguments here
